---
- name: Load platform specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - 'main.yml'
      paths:
        - 'vars'

- name: upload the new motd
  template:
    src: "{{ generic_motd_file_src }}"
    dest: "{{ generic_motd_file_dest }}"
    mode: "{{ generic_motd_mode }}"
    owner: "{{ generic_motd_owner }}"
    group: "{{ generic_motd_group }}"
    backup: true
  tags:
    - generic-motd
