---
  - name: load os specific vars
    include_vars: "{{ item }}"
    tags:
      - generic-motd
    with_first_found:
      - files:
        - "{{ ansible_os_distribution }}.yml"
        - "main.yml"

  - name: upload the new motd
    template:
      src: "{{ generic_motd_file_src }}"
      dest: "{{ generic_motd_file_dest }}"
      mode: "{{ generic_motd_mode }}"
      owner: "{{ generic_motd_owner }}"
      group: "{{ generic_motd_group }}"
      backup: yes
    tags:
      - generic-motd
