---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos6
    hostname: centos6
    image: centos:centos6
  - name: centos7
    hostname: centos7
    image: centos:centos7
  - name: ubuntu-xenial
    hostname: ubuntu-xenial
    image: ubuntu:xenial
  - name: debian-jessie
    hostname: debian-jessie
    image: debian:jessie

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
